name: Deployment

on:
  workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Install dependencies
      run: dotnet restore SteamQueryNet
    - name: Build
      run:  dotnet build -c Release --no-restore SteamQueryNet
    - name: Pack
      run: dotnet pack -c Release -o out SteamQueryNet
    - name: Push to NuGet
      run: dotnet nuget push out/*.nupkg
             --api-key ${{ secrets.NUGET_TOKEN }}
             --source https://api.nuget.org/v3/index.json
